process.env.DB_NAME = process.env.DB_NAME|| 'node_db'
process.env.DB_USER = process.env.DB_USER || 'node_user'
process.env.DB_PASSWORD = process.env.DB_PASSWORD || '123456'
process.env.DB_HOST = process.env.DB_HOST || 'localhost'
process.env.DB_PORT = process.env.DB_PORT || '3306'